import { useEffect, useRef, useState } from 'react';
import { useSession } from '../session.jsx';
import { api } from '../api.js';

// STORY-018 — Real-Time Metrics Dashboard. Polls the dashboard snapshot every
// few seconds so metrics update live as engagement arrives. STORY-017 predicted
// rates are shown alongside actuals.
const POLL_MS = 5000;

const PRIORITY_TONE = { high: 'rejected', medium: 'pending_approval', low: 'draft' };

export default function Dashboard() {
  const { userId } = useSession();
  const [d, setD] = useState(null);
  const [recs, setRecs] = useState([]);
  const [error, setError] = useState('');
  const [live, setLive] = useState(true);
  const timer = useRef(null);

  async function load() {
    try {
      const [{ dashboard }, { recommendations }] = await Promise.all([
        api.dashboard(userId),
        api.recommendations(userId),
      ]);
      setD(dashboard);
      setRecs(recommendations);
      setError('');
    } catch (e) {
      setError(e.message);
    }
  }

  useEffect(() => {
    load();
    if (live) {
      timer.current = setInterval(load, POLL_MS);
      return () => clearInterval(timer.current);
    }
  }, [userId, live]);

  return (
    <div>
      <section className="panel">
        <div className="card-head">
          <h2>
            Real-time metrics{' '}
            <span className={`live-dot ${live ? 'on' : ''}`} title={live ? 'live' : 'paused'} />
          </h2>
          <div className="card-actions">
            <button onClick={() => setLive((v) => !v)}>{live ? 'Pause' : 'Resume'} live</button>
            <button onClick={load}>Refresh</button>
          </div>
        </div>
        {error && <div className="error">{error}</div>}
        {d && (
          <>
            <p className="hint">Updated {new Date(d.generatedAt).toLocaleTimeString()} · auto-refresh every {POLL_MS / 1000}s</p>
            <div className="kpis">
              <Kpi label="Campaigns" value={d.totals.campaigns} />
              <Kpi label="Sent" value={d.totals.sent} />
              <Kpi label="Pending approval" value={d.totals.pendingApproval} />
              <Kpi label="Leads" value={d.totals.leads} />
              <Kpi label="Delivered" value={d.totals.delivered} />
              <Kpi label="Open rate" value={`${d.overallRates.openRate}%`} />
              <Kpi label="Click rate" value={`${d.overallRates.clickRate}%`} />
            </div>
          </>
        )}
      </section>

      {d && (
        <section className="panel">
          <h2>Per-campaign performance & forecast</h2>
          <table className="audit">
            <thead>
              <tr><th>Campaign</th><th>Status</th><th>Delivered</th><th>Open %</th><th>Click %</th><th>Predicted open %</th></tr>
            </thead>
            <tbody>
              {d.campaigns.map((c) => (
                <tr key={c.campaignId}>
                  <td>{c.name}</td>
                  <td><span className={`status status-${c.status}`}>{c.status.replace('_', ' ')}</span></td>
                  <td>{c.delivered}</td>
                  <td>{c.openRate}%</td>
                  <td>{c.clickRate}%</td>
                  <td className="muted">{c.predicted.openRate}%</td>
                </tr>
              ))}
              {d.campaigns.length === 0 && <tr><td colSpan={6} className="muted">No campaigns yet.</td></tr>}
            </tbody>
          </table>
        </section>
      )}

      <section className="panel">
        <h2>Optimization recommendations</h2>
        <p className="hint">Generated by the Analytics Agent from campaign performance vs. baseline.</p>
        {recs.every((r) => r.recommendations.length === 0) && <p className="hint">No campaigns to analyze yet.</p>}
        {recs.map((r) => (
          r.recommendations.length > 0 && (
            <div className="metric-block" key={r.campaignId}>
              <h3>{r.name}</h3>
              <ul className="rec-list">
                {r.recommendations.map((rec, i) => (
                  <li key={i}>
                    <span className={`status status-${PRIORITY_TONE[rec.priority] || 'draft'}`}>{rec.priority}</span>
                    <strong> {rec.message}</strong>
                    <div className="hint">{rec.rationale}</div>
                  </li>
                ))}
              </ul>
            </div>
          )
        ))}
      </section>
    </div>
  );
}

function Kpi({ label, value }) {
  return (
    <div className="kpi">
      <div className="kpi-value">{value}</div>
      <div className="kpi-label">{label}</div>
    </div>
  );
}
